### ISSUE TITLE
CentOS not supported

### ISSUE THREAD

**Issue by schlitzered** [cohdjn/cisecurity#1]
hey,

one of the problems is the hiera.yaml

is: path: 'os/%{facts.os.name}%{facts.os.release.major}.yaml'

should be: path: 'os/%{facts.os.family}%{facts.os.release.major}.yaml'

the other issue is that facts.d/cisecurity relies on the subscription manager to be installed.

after this, is stopped testing.

Kind regards,

**Comment by dn89000** [comment]
Change your Puppetfile to reference the Github site rather than the Forge and let me know if the latest commit fixes your problem.
