### ISSUE TITLE
Two or more users for sshd_allowed_users

### ISSUE THREAD

**Issue by mpsspsnl** [cohdjn/cisecurity#3]
I have tried several possibilities to specify two or more users for the sshd_allowed_users parameter in RedHat7.yaml.
For example:
`cisecurity::redhat7::services::sshd_allowed_users:`
  `- 'user1'`
  `- 'user2'`
Or:
`cisecurity::redhat7::services::sshd_allowed_users: ['user1', 'user2']`

But each time I get this error:

Notice: /Stage[main]/Cisecurity::Redhat7::Services/Sshd_config[AllowUsers]/value: value changed ['user1'] to 'user1 user2'
Debug: Puppet::Type::Sshd_config::ProviderAugeas: Save failure details:
/augeas/files/etc/ssh/sshd_config/error/path = /files/etc/ssh/sshd_config/AllowUsers
/augeas/files/etc/ssh/sshd_config/error/lens = /opt/puppetlabs/puppet/share/augeas/lenses/dist/sshd.aug:84.7-.46:
/augeas/files/etc/ssh/sshd_config/error/message = Failed to match

{ /[0123456789]+/ = /[^\001-\004\t\n ]+/ }*
  with tree
{ "1" = "user1 user2" }
Error: /Stage[main]/Cisecurity::Redhat7::Services/Sshd_config[AllowUsers]: Could not evaluate: Failed to save Augeas tree to file. See debug logs for details.

If have tested with only augeasproviders_ssh and there is no problem specifying more users.
What am I doing wrong?

puppet --version
4.10.9

**Comment by dn89000** [comment]
I committed a change to the Puppet code that should fix this problem.  Please change your Puppetfile to reference the Github repo and test.  I'm not committing to the Forge just yet but will either today or next week as I have other changes to put in place.

**Comment by mpsspsnl** [comment]
OK, thanks a lot.

I also made some minor changes to comply with CIS standards. Don't know if you are interested in that?
[cisecurity_changes.txt](https://github.com/cohdjn/cisecurity/files/1685804/cisecurity_changes.txt)

**Comment by dn89000** [comment]
Always interested.  I see they released an updated set of controls so I'll be digging through those over the next few days.  In the meantime, did the recent commit fix the problem?

**Comment by mpsspsnl** [comment]
Yes, it fixed the problem. Thanks for that. Little disappointed that I couldn't solve this myself... But I am learning.

**Comment by dn89000** [comment]
We all are!   :)

If you find anything else, open an issue and I'll take a look.
