### ISSUE TITLE
puppet 5 compatibility

### ISSUE THREAD

**Issue by phillroberts** [cohdjn/cisecurity#4]
The module is only compatible with puppet >= 4.7.0 < 5.0.0 but the only available versions of puppet I can find in any yum repository is 3.x (epel repo) or 5.x (puppet labs repo).  

Looking at the code I can see it's clearly not compatible with 3.x so I installed puppet 5.3.3 to give it a try.  The following is the output when following the installation instructions from the forge.
```
puppet module install cohdjn-cisecurity --version 0.6.5
Notice: Preparing to install into /etc/puppetlabs/code/environments/production/modules ...
Notice: Downloading from https://forgeapi.puppet.com ...
Error: Could not install module 'cohdjn-cisecurity' (???)
  No version of 'cohdjn-cisecurity' can satisfy all dependencies
    Use `puppet module install --ignore-dependencies` to install only this module
```

Any ETA on when this can be puppet 5 compatible?

**Comment by dn89000** [comment]
The current version is already Puppet 5 compatible.  I have a few more commits to make before updating the version on the Forge but you can run ``puppet module install --ignore-dependencies`` in the meantime to get it installed.
